### ISSUE TITLE
Make header bar look nicer

### ISSUE THREAD

**Issue by SeanGolez** [jeffreyHoelzel/LouiesRatings#110]
I got some feedback that the header bar looks a little empty and the homepage button is not obvious that it goes back to the homepage. 

We could take some inspiration from the Peoplesoft header bar:
![image](https://github.com/user-attachments/assets/af7e923a-5293-4052-adfb-bf8d612a4edc)

**Comment by LukeBowen85** [comment]
Done with PR #112
