### ISSUE TITLE
Clean up backend functions

### ISSUE THREAD

**Issue by SeanGolez** [jeffreyHoelzel/LouiesRatings#98]
I was inspired by today's lecture to make our code more readable 🤓. We can probably just separate each group of functions into their own file to free up app.py.

**Comment by jeffreyHoelzel** [comment]
Was thinking about this too after yesterday's lecture lol, I think the database.py file is fine since everything is pretty much related to database querying or setting up. But I agree about app.py, maybe we could plan to do a refactor after implementation 2.

**Comment by SeanGolez** [comment]
I think that we should free up database.py too, since a lot of the functions in there are related to a function in app.py, so they are just exist together in their own file.
